---
- name: Generation d'un certificat pour le serveur signé par le nouveau CA de la Registry
  shell:
          openssl x509 -req -in /etc/gitlab/ssl/registry.example.com.csr -CAkey /etc/gitlab/ssl/alinuxien-registry.ca.key -CA /vagrant/alinuxien-registry-ca.cer -CAcreateserial -CAserial /etc/gitlab/ssl/registry.example.com.serial -out /etc/gitlab/ssl/registry.example.com.crt -days 3650 -sha256 -extfile /vagrant/registry.example.com.sslv3.txt


