---
- name: "Installation du paquet GitLab Runner"
  apt:
          name: "gitlab-runner"
          state: present

- include_tasks: "{{ item }}" 
  with_items:
          - dir_certs.yml
          - cert_copy.yml
          - ca_cert_copy.yml
          - ca_cert_copy_global.yml
          - add_docker_group.yml
          - docker_service_restart.yml

